name: Brakeman

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - 'master'

jobs:
  brakeman:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - run: echo "::set-output name=RUBY_VERSION::$(cat .ruby-version)"
        id: ruby_version
      - name: Set up Ruby from .ruby-version file
        uses: ruby/setup-ruby@v1
        with:
         ruby-version: "${{ steps.ruby_version.outputs.RUBY_VERSION }}"
      - name: Brakeman install
        run: gem install brakeman
      - name: brakeman
        id: brakeman
        run: |
          brakeman -w3 --color -q --force
          if [ $? -ne 0 ]; then return 1; fi
